### ISSUE TITLE
Using availability type "chat" instead of "online"

### ISSUE THREAD

**Issue by crypoxyz** [flooowd/irf-tools#2]
I would recommend to use the "chat" availability instead of "online".
If the availability gets changed to "online" the user cannot change it to "away" with the inbuilt LCU feature.
Thats why I would change following part of the "main.py" file:

```py
def availability(self):
        availabilitys = ['online', 'offline', 'mobile']
        data = api.get('/lol-chat/v1/me').json()
```

to:

```py
def availability(self):
        availabilitys = ['chat', 'offline', 'mobile']
        data = api.get('/lol-chat/v1/me').json()
```

That gives the user the ability to still go "away" and back "online" from inside the LCU. :)

**Comment by flooowd** [comment]
ok, create a pull request please
